version: "3.4"
services:
  dask-scheduler:
    build:
      context: .
      dockerfile: ./dask/Dockerfile
    hostname: dask-scheduler
    tty: true
    networks:
      - inbound
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - shared_data:/shared_drive
      - ./shared_drive:/shared_drive
    command: ["dask-scheduler"]
#############################################################################
  dask-worker:
    build:
      context: .
      dockerfile: ./dask/Dockerfile
    tty: true
    networks:
      - inbound
    depends_on:
      - dask-scheduler
    volumes:
      - shared_data:/shared_drive
      - ./shared_drive:/shared_drive
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
networks:
      inbound:


volumes:
    shared_data: {}
